services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_prod
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: product_db
    volumes:
      - mongo_prod_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ping: 1})' || mongo --eval 'db.runCommand({ping: 1})'"]
      interval: 10s
      timeout: 5s
      retries: 5

  product-api:
    image: thaonguyen207/product-api:latest
    container_name: product_api_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/product_db
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongo_prod_data:

networks:
  app-network:
    driver: bridge